name: Feature Request
description: Suggest a new feature / 请求添加新功能
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature you'd like / 描述你希望添加的功能
      description: What problem does this feature solve? / 请描述此功能要解决的问题。
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: Related suggestions / 参考建议
      description: Provide examples, references, or similar tools. / 请提供参考、示例或其他工具的类似功能。

  - type: textarea
    id: extra
    attributes:
      label: Additional context / 补充信息
