# ruff: noqa: E501
# Auto-generated by scripts/gen_url_testcase.py

from dataclasses import dataclass

import pytest

from novelkit.infra.url_resolver import resolve_book_url


@dataclass(frozen=True)
class SuccessCase:
    url: str
    site_key: str
    book_id: str | None
    chap_id: str | None = None


# fmt: off
CASES_SUCCESS = [
    SuccessCase("http://www.aaatxt.com/shu/24514.html", "aaatxt", "24514", None),
    SuccessCase("http://www.aaatxt.com/yuedu/24514_1.html", "aaatxt", "24514", "1"),
    SuccessCase("https://www.akatsuki-novels.com/stories/index/novel_id~103", "akatsuki_novels", "103", None),
    SuccessCase("https://www.akatsuki-novels.com/stories/view/163722/novel_id~103", "akatsuki_novels", "103", "163722"),
    SuccessCase("https://www.akatsuki-novels.com/stories/index/novel_id~14222#bottom", "akatsuki_novels", "14222", None),
    SuccessCase("https://www.akatsuki-novels.com/stories/view/138014/novel_id~14222#bottom", "akatsuki_novels", "14222", "138014"),
]

CASES_NONE = [
    "http://www.aaatxt.com/",
    "https://www.akatsuki-novels.com/",
]

CASES_INVALID = [
    # URLs with no rule should return None
    "https://www.unknownsite.com/book/123.html",
    "https://example.org/unrelated/page",
    "not a url",
    "",
]
# fmt: on


@pytest.mark.parametrize("case", CASES_SUCCESS)
def test_resolver_extracts_expected_ids(case: SuccessCase):
    result = resolve_book_url(case.url)
    assert result is not None, f"{case.url}: expected BookURLInfo, got None"
    assert result["site_key"] == case.site_key
    assert result["book_id"] == case.book_id
    assert result["chapter_id"] == case.chap_id, (
        f"{case.url}: expected chapter_id={case.chap_id}, got {result['chapter_id']}"
    )


@pytest.mark.parametrize("url", CASES_NONE)
def test_resolver_returns_none_for_unmatched_paths(url):
    assert resolve_book_url(url) is None


@pytest.mark.parametrize("url", CASES_INVALID)
def test_resolver_handles_invalid_urls(url: str):
    result = resolve_book_url(url)
    assert result is None, f"{url}: expected None for invalid URL"
