#!/usr/bin/env python3
"""
python scripts/gen_url_testcase.py
"""

# ruff: noqa: E501

import tomllib
from pathlib import Path

CONFIG_DIR = Path(__file__).parent / "data" / "supported_sites"
OUT_PATH = Path("tests/infra/test_url_resolver.py")
S = "    "

TEMPLATE_CODE = """\
# ruff: noqa: E501
# Auto-generated by scripts/gen_url_testcase.py

from dataclasses import dataclass

import pytest

from novelkit.infra.url_resolver import resolve_book_url


@dataclass(frozen=True)
class SuccessCase:
    url: str
    site_key: str
    book_id: str | None
    chap_id: str | None = None


# fmt: off
{code}

CASES_INVALID = [
    # URLs with no rule should return None
    "https://www.unknownsite.com/book/123.html",
    "https://example.org/unrelated/page",
    "not a url",
    "",
]
# fmt: on


@pytest.mark.parametrize("case", CASES_SUCCESS)
def test_resolver_extracts_expected_ids(case: SuccessCase):
    result = resolve_book_url(case.url)
    assert result is not None, f"{{case.url}}: expected BookURLInfo, got None"
    assert result["site_key"] == case.site_key
    assert result["book_id"] == case.book_id
    assert result["chapter_id"] == case.chap_id, (
        f"{{case.url}}: expected chapter_id={{case.chap_id}}, got {{result['chapter_id']}}"
    )


@pytest.mark.parametrize("url", CASES_NONE)
def test_resolver_returns_none_for_unmatched_paths(url):
    assert resolve_book_url(url) is None


@pytest.mark.parametrize("url", CASES_INVALID)
def test_resolver_handles_invalid_urls(url: str):
    result = resolve_book_url(url)
    assert result is None, f"{{url}}: expected None for invalid URL"
"""


def quote_or_none(val: str | None) -> str:
    """Return 'None' or quoted string like `"value"`."""
    return "None" if val is None else f'"{val}"'


def load_toml(path: Path) -> dict:
    return tomllib.loads(path.read_text(encoding="utf-8"))


def main() -> None:
    succ_lines: list[str] = []
    none_lines: list[str] = []

    for toml_file in sorted(CONFIG_DIR.glob("*.toml")):
        data = load_toml(toml_file)
        meta = data.get("meta", {})
        site_key = meta.get("key")
        if not site_key:
            continue

        # ------------------------
        # SUCCESS CASES
        # ------------------------
        examples = data.get("examples", [])
        for item in examples:
            url = item["url"]
            book_id = item.get("book_id")
            chap_id = item.get("chapter_id")

            succ_lines.append(
                f'{S}SuccessCase("{url}", "{site_key}", '
                f"{quote_or_none(book_id)}, {quote_or_none(chap_id)}),"
            )

        # ------------------------
        # NONE CASES
        # ------------------------
        homepage = meta.get("homepage")
        if homepage:
            none_lines.append(f'{S}"{homepage}",')

        for host in meta.get("alt_domains", []):
            none_lines.append(f'{S}"{host}",')

    lines: list[str] = [
        "CASES_SUCCESS = [",
        *succ_lines,
        "]",
        "",
        "CASES_NONE = [",
        *none_lines,
        "]",
    ]

    OUT_PATH.write_text(
        TEMPLATE_CODE.format(code="\n".join(lines)),
        encoding="utf-8",
        newline="\n",
    )
    print(f"Generated: {OUT_PATH}")


if __name__ == "__main__":
    main()
